name: libschemaregistry
lang: unknown
lang_version: unknown
git:
  enable: true
github:
  enable: true
semaphore:
  enable: true
  pipeline_enable: false
codeowners:
  enable: true
renovatebot:
  enable: true
  automerge:
    enable: false
