/**
 * Confluent Schema Registry
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.13.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ClientConfiguration.h
 *
 * This class represents a single item of a multipart-formdata request.
 */

#pragma once

#include <cpr/cpr.h>

#include <cstdint>
#include <map>
#include <memory>
#include <optional>
#include <string>
#include <vector>

namespace schemaregistry::rest {

// Forward declaration
class OAuthProvider;

/**
 * Configuration for Schema Registry client.
 *
 * Authentication methods are mutually exclusive:
 * - Basic Auth (setBasicAuth) - API Key/Secret authentication
 * - OAuth Provider (setOAuthProvider) - OAuth 2.0 with automatic token refresh
 * - Bearer Token (setBearerAccessToken) - Static bearer token (legacy, no auto-refresh)
 *
 * Setting any authentication method automatically clears previously configured methods.
 * Only one authentication method can be active at a time.
 */
class ClientConfiguration {
  public:
    ClientConfiguration(const std::vector<std::string> &base_urls);
    virtual ~ClientConfiguration();

    std::vector<std::string> getBaseUrls() const;

    /**
     * Basic authentication (API Key/Secret).
     * Setting this clears OAuth Provider and Bearer Token.
     */
    std::optional<std::pair<std::string, std::string>> getBasicAuth() const;
    void setBasicAuth(
        const std::optional<std::pair<std::string, std::string>> &basic_auth);

    /**
     * OAuth provider for automatic token management.
     * Setting this clears Basic Auth and Bearer Token.
     * Supports static tokens and OAuth Client Credentials flow.
     */
    std::shared_ptr<OAuthProvider> getOAuthProvider() const;
    void setOAuthProvider(std::shared_ptr<OAuthProvider> provider);

    /**
     * Static bearer token (legacy, no automatic refresh).
     * Setting this clears Basic Auth and OAuth Provider.
     * For automatic token management, use setOAuthProvider instead.
     */
    std::optional<std::string> getBearerAccessToken() const;
    void setBearerAccessToken(
        const std::optional<std::string> &bearer_access_token);

    // Cache configuration getters and setters
    std::uint64_t getCacheCapacity() const;
    void setCacheCapacity(std::uint64_t cache_capacity);

    std::uint64_t getCacheLatestTtlSec() const;
    void setCacheLatestTtlSec(std::uint64_t cache_latest_ttl_sec);

    // Retry configuration getters and setters
    std::uint32_t getMaxRetries() const;
    void setMaxRetries(std::uint32_t max_retries);

    std::uint32_t getRetriesWaitMs() const;
    void setRetriesWaitMs(std::uint32_t retries_wait_ms);

    std::uint32_t getRetriesMaxWaitMs() const;
    void setRetriesMaxWaitMs(std::uint32_t retries_max_wait_ms);

    std::shared_ptr<cpr::Session> getSession() const;
    void setSession(std::shared_ptr<cpr::Session>);

    bool operator==(const ClientConfiguration &other) const;
    bool operator!=(const ClientConfiguration &other) const;

  protected:
    std::vector<std::string> baseUrls_;

    std::optional<std::pair<std::string, std::string>> basic_auth_;
    std::optional<std::string> bearer_access_token_;
    std::shared_ptr<OAuthProvider> oauth_provider_;

    std::uint64_t cache_capacity_;
    std::uint64_t cache_latest_ttl_sec_;

    std::uint32_t max_retries_;
    std::uint32_t retries_wait_ms_;
    std::uint32_t retries_max_wait_ms_;

    std::shared_ptr<cpr::Session> session_;
};

}  // namespace schemaregistry::rest
