/**
 * Confluent Schema Registry
 * No description provided (generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.13.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RestClient.h
 *
 * This is an API client responsible for stating the HTTP calls
 */

#pragma once

#include <chrono>
#include <functional>
#include <memory>
#include <mutex>
#include <vector>

#include "schemaregistry/rest/ClientConfiguration.h"
#include "schemaregistry/rest/RestException.h"

namespace schemaregistry::rest {

class RestClient {
  public:
    RestClient(
        std::shared_ptr<const ClientConfiguration> configuration = nullptr);
    virtual ~RestClient();

    std::shared_ptr<const ClientConfiguration> getConfiguration() const;

    cpr::Response sendRequestUrls(
        const std::string &path, const std::string &method,
        const std::vector<std::pair<std::string, std::string>> &query,
        const std::map<std::string, std::string> &headers,
        const std::string &body) const;

  private:
    cpr::Response sendRequest(
        const std::string &url, const std::string &method,
        const std::vector<std::pair<std::string, std::string>> &query,
        const std::map<std::string, std::string> &headers,
        const std::string &body) const;

    cpr::Response tryRequest(
        const std::string &base_url, const std::string &path,
        const std::string &method,
        const std::vector<std::pair<std::string, std::string>> &query,
        const std::map<std::string, std::string> &headers,
        const std::string &body) const;

  protected:
    std::shared_ptr<const ClientConfiguration> configuration_;
    mutable std::mutex session_mutex_;
};

}  // namespace schemaregistry::rest
